AWSTemplateFormatVersion: '2010-09-09'
Resources:
  AdminsGroup:
    Type: "AWS::IAM::Group"
    Properties:
      GroupName: "Administrators"
  DevelopersGroup:
    Type: "AWS::IAM::Group"
    Properties:
      GroupName: "Developers"
  UsersGroup:
    Type: "AWS::IAM::Group"
    Properties:
      GroupName: "Users"
      Policies:
        - PolicyName: group-user-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "iam:ListUsers"
                  - "iam:GetAccountPasswordPolicy"
                Resource: "*"
              - Effect: Allow
                Action:
                  - "iam:*AccessKey*"
                  - "iam:ChangePassword"
                  - "iam:GetUser"
                  - "iam:*ServiceSpecificCredential*"
                  - "iam:*SigningCertificate*"
                Resource:
                  Fn::Sub:
                    - arn:aws:iam::${awsid}:user/${awsuser}
                    - { awsid: !Ref "AWS::AccountId", awsuser: "${aws:username}" }
              - Effect: Allow
                Action:
                  - "iam:CreateVirtualMFADevice"
                  - "iam:EnableMFADevice"
                  - "iam:ResyncMFADevice"
                  - "iam:DeleteVirtualMFADevice"
                Resource:
                  - Fn::Sub:
                      - arn:aws:iam::${awsid}:mfa/${awsuser}
                      - { awsid: !Ref "AWS::AccountId", awsuser: "${aws:username}" }
                  - Fn::Sub:
                      - arn:aws:iam::${awsid}:user/${awsuser}
                      - { awsid: !Ref "AWS::AccountId", awsuser: "${aws:username}" }
              - Effect: Allow
                Action:
                  - "iam:DeactivateMFADevice"
                Resource:
                  - Fn::Sub:
                      - arn:aws:iam::${awsid}:mfa/${awsuser}
                      - { awsid: !Ref "AWS::AccountId", awsuser: "${aws:username}" }
                  - Fn::Sub:
                      - arn:aws:iam::${awsid}:user/${awsuser}
                      - { awsid: !Ref "AWS::AccountId", awsuser: "${aws:username}" }
                Condition:
                  Bool:
                    "aws:MultiFactorAuthPresent": true
              - Effect: Allow
                Action:
                  - "iam:ListMFADevices"
                  - "iam:ListVirtualMFADevices"
                Resource: "*"
              - Effect: Allow
                Action:
                  - "iam:*LoginProfile"
                  - "iam:*SSHPublicKey*"
                Resource:
                  Fn::Sub:
                    - arn:aws:iam::${awsid}:user/${awsuser}
                    - { awsid: !Ref "AWS::AccountId", awsuser: "${aws:username}" }
              - Effect: Allow
                Action:
                  - "iam:ListAccount*"
                  - "iam:GetAccountSummary"
                  - "iam:GetAccountPasswordPolicy"
                  - "iam:ListUsers"
                Resource: "*"
